import 'package:hive/hive.dart';

part 'equipment.g.dart'; // This part file will be generated by Hive

@HiveType(typeId: 5)
class Equipment extends HiveObject {
  @HiveField(0)
  final String name; // Equipment name

  @HiveField(1)
  late final int quantity; // Quantity of the equipment

  @HiveField(2)
  final String unit; // Unit for heavy equipment (e.g., kg, ton, etc.)

  @HiveField(3)
  final String type; // Type of equipment (Heavy or Light)

  // Constructor
  Equipment({
    required this.name,
    required this.quantity,
    required this.unit,
    required this.type,
  });
}
