import 'package:hive/hive.dart';

part 'user.g.dart'; // This part file is generated by Hive

@HiveType(typeId: 0) // Unique typeId for the User class
class User {
  @HiveField(0)
  final String firstName;

  @HiveField(1)
  final String lastName;

  @HiveField(2)
  final String email;

  @HiveField(3)
  final String phoneNumber;

  @HiveField(4)
  final String password;

  @HiveField(5)
  final String role;

  @HiveField(6)
  final String farmName;

  @HiveField(7)
  final String location;

  @HiveField(8)
  final String name;

  User({
    required this.firstName,
    required this.lastName,
    required this.email,
    required this.phoneNumber,
    required this.password,
    required this.role,
    required this.farmName,
    required this.location,
    required this.name,
  });
}
